### ISSUE TITLE
fixing all eslint errors 

### ISSUE THREAD

**Issue by Yousef-Salah** [Yousef-Salah/freepik-clone#103]
## Problem:
Vercel cannot build project because eslint errors
## Expected Behavior
- All eslint errors will be fixed
- `npm run build` command, will be performed without any problem
## Steps to Reproduce the Problem
Open all project files that contains any of eslint errors then fix these erros.
## Specifications
  - Desired merge branch: **`develop`**

**Comment by OmarMHawash** [comment]
Actually I wasn't working on something.
Just if you can merge (or I would do) the last PR. Try to finish it as soon as possible.

Cheers!

**Comment by Yousef-Salah** [comment]
@OmarMHawash I merged it, Good Job.
